#version: 1.5.2-rc{build}
environment:
  matrix:
    - WEEWX: weewx-4.0.0b18.tar.gz
      PYTHON: 2.7
      APPVEYOR_BUILD_WORKER_IMAGE: Ubuntu1804
      WEEWX_URL: http://www.weewx.com/downloads/development_versions/
      
    - WEEWX: weewx-4.0.0b18.tar.gz
      PYTHON: 3.6
      APPVEYOR_BUILD_WORKER_IMAGE: Ubuntu1804
      WEEWX_URL: http://www.weewx.com/downloads/development_versions/
      COVERALLS_UPLOAD: true
      SONAR_UPLOAD: true
      
    - WEEWX: weewx-3.9.2.tar.gz
      PYTHON: 2.7
      APPVEYOR_BUILD_WORKER_IMAGE: Ubuntu1804
      WEEWX_URL: http://www.weewx.com/downloads/released_versions/
      
stack: python %PYTHON%
install:
  - sh: appveyor/install.sh

build_script:
  - sh: appveyor/build_script.sh  

test_script:
- sh: >-
    PYTHONPATH=bin:./weewx/bin nosetests ./bin/user/tests/func --exe --exclude=setup --cover-package=user.MQTTSubscribe --with-xunit --with-coverage --cover-branches --cover-xml --xunit-file=nosetests2.xml --verbosity=3

    find "$APPVEYOR_BUILD_FOLDER" -type f -name 'nosetests2.xml' -print0 | xargs -0 -I '{}' curl -F 'file=@{}' "https://ci.appveyor.com/api/testresults/junit/$APPVEYOR_JOB_ID"

    PYTHONPATH=bin nosetests ./bin/user/tests/unit --exe --exclude=setup --cover-package=user.MQTTSubscribe --with-xunit --with-coverage --cover-branches --cover-xml --verbosity=3

    find "$APPVEYOR_BUILD_FOLDER" -type f -name 'nosetests.xml' -print0 | xargs -0 -I '{}' curl -F 'file=@{}' "https://ci.appveyor.com/api/testresults/junit/$APPVEYOR_JOB_ID"

after_test:
  - sh: appveyor/after_test.sh

on_finish:
  - sh: appveyor/on_finish.sh
   