version: 1.5.2-rc{build}
#image: Ubuntu1804
# stack: python 3.7, python 2.7
#stack: python 3.7
environment:
  matrix:
    - WEEWX: weewx-4.0.0b18.tar.gz
      PYTHON: 2.7
      WEEWX_URL: http://www.weewx.com/downloads/development_versions/
      APPVEYOR_BUILD_WORKER_IMAGE: Ubuntu1804
    - WEEWX: weewx-4.0.0b18.tar.gz
      PYTHON: 3.6
      WEEWX_URL: http://www.weewx.com/downloads/development_versions/
      APPVEYOR_BUILD_WORKER_IMAGE: Ubuntu1804
    - WEEWX: weewx-3.9.2.tar.gz
      PYTHON: 2.7
      WEEWX_URL: http://www.weewx.com/downloads/released_versions/
      APPVEYOR_BUILD_WORKER_IMAGE: Ubuntu1804
stack: python %PYTHON%
install:
  - sh: appveyor/install.sh
build_script:
- sh: >-
    echo "Running pip installs"

    pip install configobj --quiet

    pip install paho-mqtt --quiet

    pip install mock --quiet

    pip install pylint --quiet

    pip install coveralls --quiet

    pip install nose --quiet

    pip install coverage --quiet

    #export PATH=/home/appveyor/.local/bin:$PATH

    #./coverage.sh

    echo "Running weewx install"

    wget  $WEEWX_URL/$WEEWX

    mkdir weewx

    tar xfz $WEEWX --strip-components=1 -C weewx

    sudo apt-get --assume-yes install mosquitto

    #mosquitto -h

    # mosquitto &

    PYTHONPATH=bin:./weewx/bin nosetests ./bin/user/tests/func --exe --exclude=setup --cover-package=user.MQTTSubscribe --with-xunit --with-coverage --cover-branches --cover-xml --xunit-file=nosetests2.xml --verbosity=3

    find "$APPVEYOR_BUILD_FOLDER" -type f -name 'nosetests2.xml' -print0 | xargs -0 -I '{}' curl -F 'file=@{}' "https://ci.appveyor.com/api/testresults/junit/$APPVEYOR_JOB_ID"

    #PYTHONPATH=bin:./weewx/bin nosetests ./bin/user/tests/func/test_get_data.py --exe --exclude=setup --cover-package=user.MQTTSubscribe --with-xunit --with-coverage --cover-branches --cover-xml --xunit-file=single.xml --verbosity=3

    #find "$APPVEYOR_BUILD_FOLDER" -type f -name 'single.xml' -print0 | xargs -0 -I '{}' curl -F 'file=@{}' "https://ci.appveyor.com/api/testresults/junit/$APPVEYOR_JOB_ID"

    PYTHONPATH=bin nosetests ./bin/user/tests/unit --exe --exclude=setup --cover-package=user.MQTTSubscribe --with-xunit --with-coverage --cover-branches --cover-xml --verbosity=3

    find "$APPVEYOR_BUILD_FOLDER" -type f -name 'nosetests.xml' -print0 | xargs -0 -I '{}' curl -F 'file=@{}' "https://ci.appveyor.com/api/testresults/junit/$APPVEYOR_JOB_ID"

    #appveyor PushArtifact -Path ./nosetests.xml -FileName nosetests.xml

    #appveyor AddTest -Name xUnit -FileName nosetests.xml -Framework xUnit

    #appveyor AddTest -Name JUnit -FileName $APPVEYOR_BUILD_FOLDER/nosetests.xml -Framework JUnit

    #appveyor AddTest -Name JUnitX -FileName nosetestsx.xml -Framework JUnitx

    #appveyor AddTest -Name NUnit -FileName nosetests.xml -Framework NUnit

    #appveyor AddTest -Name single -FileName single.xml -Framework JUnit



    #appveyor PushArtifact -Path ./nosetests2.xml -FileName nosetests2.xml

    #appveyor AddTest -Name xUnit2 -FileName nosetests2.xml -Framework xUnit

    #appveyor UpdateTest -Name JUnit2 -FileName nosetests2.xml -Framework JUnit

    #appveyor AddTest -Name NUnit2 -FileName nosetests2.xml -Framework NUnit

    #appveyor -h

    cp nosetests.xml xxxx.xml

    # sed -i 's/filename="/filename=".\//g' coverage.xml

    sed -i 's/classname="/classname="bin\/user\/tests\/unit./g' nosetests.xml

    sed -i 's/classname="/classname="bin\/user\/tests\/func./g' nosetests2.xml

    #cp nosetests.xml nosetests2.xml


    coveralls


    pylint ./bin/user/MQTTSubscribe.py -r n --msg-template="{path}:{line}: [{msg_id}({symbol}), {obj}] {msg}" | tee pylint.txt


    sonar-scanner \
      -Dsonar.organization=bellrichm \
      -Dsonar.projectKey=bellrichm_WeeWX-MQTTSubscribe \
      -Dsonar.sources=./bin/user/MQTTSubscribe.py \
      -Dsonar.tests=./bin/user/tests \
      -Dsonar.language=py \
      -Dsonar.python.xunit.reportPath=nosetests*.xml \
      -Dsonar.python.xunit.skipDetails=false \
      -Dsonar.python.coverage.reportPaths=coverage.xml \
      -Dsonar.python.coveragePlugin=cobertura \
      -Dsonar.python.pylint.reportPath=pylint.txt \
      -Dsonar.host.url=https://sonarcloud.io \
      -Dsonar.login=$SKEY \
      #-X


    #-Dsonar.python.xunit.reportPath=nosetest*.xml \

    #-Dsonar.python.xunit.reportPath=nosetests.xml

    #-Dsonar.python.coverage.reportPath=coverage.xml

    #-Dsonar.python.coveragePlugin=cobertura


    # ls -la


    #cat nosetests2.xml

    #cat nosetests.xml


    python --version

    pip --version

    python2 --version

    python3 --version

    pip2 --version

    pip3 --version

    which python

    which python2

    which python3

    which pip

    which pip2

    which pip3

    # ls -la /usr/sbin
    
    which appveyor
    
    pwd



#init:
#  - sh: curl -sflL 'https://raw.githubusercontent.com/appveyor/ci/master/scripts/enable-ssh.sh' | bash -e -    

on_finish:
  - sh: appveyor/on_finish.sh
   