version: 1.5.2-rc{build}
image: Ubuntu1804
# stack: python 3.7, python 2.7
stack: python 3.7
build_script:
- sh: >-
    export SONAR_SCANNER_VERSION=4.2.0.1873

    export SONAR_SCANNER_HOME=$HOME/.sonar/sonar-scanner-$SONAR_SCANNER_VERSION-linux

    echo "Running sonar runner install"
    
    curl --create-dirs -sSLo $HOME/.sonar/sonar-scanner.zip https://binaries.sonarsource.com/Distribution/sonar-scanner-cli/sonar-scanner-cli-$SONAR_SCANNER_VERSION-linux.zip

    unzip -qq -o $HOME/.sonar/sonar-scanner.zip -d $HOME/.sonar/

    export PATH=$SONAR_SCANNER_HOME/bin:$PATH

    export SONAR_SCANNER_OPTS="-server"

    echo "Running pip installs"

    pip install configobj --quiet

    pip install paho-mqtt --quiet

    pip install mock --quiet

    pip install pylint --quiet

    pip install coveralls --quiet

    pip install nose --quiet

    pip install coverage --quiet

    #export PATH=/home/appveyor/.local/bin:$PATH

    #./coverage.sh


    PYTHONPATH=bin nosetests ./bin/user/tests/unit --exe --exclude=setup --cover-package=user.MQTTSubscribe --with-xunit --with-coverage --cover-branches --cover-xml --verbosity=3

    appveyor PushArtifact -Path ./ -FileName nosetests.xml

    appveyor AddTest -Name nosetests.xml -FileName nosetests.xml -Framework xUnit

    appveyor AddTest -Name nosetests2.xml -FileName nosetests.xml -Framework JUnit

    # sed -i 's/filename="/filename=".\//g' coverage.xml

    sed -i 's/classname="/classname="bin\/user\/tests\/unit./g' nosetests.xml

    cp nosetests.xml nosetests2.xml


    coveralls


    pylint ./bin/user/MQTTSubscribe.py -r n --msg-template="{path}:{line}: [{msg_id}({symbol}), {obj}] {msg}" | tee pylint.txt


    sonar-scanner \
      -Dsonar.organization=bellrichm \
      -Dsonar.projectKey=bellrichm_WeeWX-MQTTSubscribe \
      -Dsonar.sources=./bin/user/MQTTSubscribe.py \
      -Dsonar.tests=./bin/user/tests/unit \
      -Dsonar.language=py \
      -Dsonar.python.xunit.reportPath=nosetest*.xml \
      -Dsonar.python.xunit.skipDetails=false \
      -Dsonar.python.coverage.reportPaths=coverage.xml \
      -Dsonar.python.coveragePlugin=cobertura \
      -Dsonar.python.pylint.reportPath=pylint.txt \
      -Dsonar.host.url=https://sonarcloud.io \
      -Dsonar.login=$SKEY \
      #-X

    #-Dsonar.python.xunit.reportPath=nosetests.xml

    #-Dsonar.python.coverage.reportPath=coverage.xml

    #-Dsonar.python.coveragePlugin=cobertura


    ls -la

    find "$APPVEYOR_BUILD_FOLDER" -type f -name 'nosetests.xml' -print0 | xargs -0 -I '{}' curl -F 'file=@{}' "https://ci.appveyor.com/api/testresults/xunit/$APPVEYOR_JOB_ID"


    cat nosetests.xml




    python --version

    pip --version

    python2 --version

    python3 --version

    pip2 --version

    pip3 --version

    which python

    which python2

    which python3

    which pip

    which pip2

    which pip3
test: off