environment:
  SONAR_SCANNER_VERSION: 4.2.0.1873
  SONAR_SCANNER_OPTS: -server
  matrix:
    - WEEWX: 4.0.0b18
      PYTHON: 3.6
      APPVEYOR_BUILD_WORKER_IMAGE: Ubuntu1804
      WEEWX_URL: http://www.weewx.com/downloads/development_versions/
      COVERALLS_UPLOAD: true
      SONAR_UPLOAD: true

    - WEEWX: 4.0.0b18
      PYTHON: 2.7
      APPVEYOR_BUILD_WORKER_IMAGE: Ubuntu1804
      WEEWX_URL: http://www.weewx.com/downloads/development_versions/

    - WEEWX: 3.9.2
      PYTHON: 2.7
      APPVEYOR_BUILD_WORKER_IMAGE: Ubuntu1804
      WEEWX_URL: http://www.weewx.com/downloads/released_versions/
      
stack: python %PYTHON%

init:
  # Need to be here to be available in all scripts
  - sh: export SONAR_SCANNER_HOME=$HOME/.sonar/sonar-scanner-$SONAR_SCANNER_VERSION-linux
  - sh: export PATH=$SONAR_SCANNER_HOME/bin:$PATH

install:
  - sh: appveyor/install.sh

build_script:
  - sh: appveyor/build_script.sh  

test_script:
- sh: appveyor/test_script.sh

after_test:
  - sh: appveyor/after_test.sh

on_finish:
  - sh: appveyor/on_finish.sh
   